12/17/23
extraEnv: |-
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: KC_HTTPS_CERTIFICATE_FILE
    value: "/opt/keycloak/conf/tls.crt"
  - name: KC_HTTPS_CERTIFICATE_KEY_FILE
    value: "/opt/keycloak/conf/tls.key"
  - name: KC_HTTPS_TRUST_STORE_FILE
    value: "/opt/keycloak/conf/truststore.jks"
  - name: KC_HTTPS_TRUST_STORE_PASSWORD
    value: "password"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: KC_CACHE
    value: "ispn"
  - name: KC_CACHE_STACK
    value: "kubernetes"
  - name: KC_HOSTNAME
    value: "keycloak.10-7-2-63.sslip.io"
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/auth"
  - name: KC_HTTP_ENABLED
    value: "false"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  - name: KC_HTTPS_CLIENT_AUTH
    value: request
  - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: "-Djgroups.dns.query=keycloak-keycloakx-headless.keycloak.svc.cluster.local"
  - name: KC_LOG_LEVEL
    value: "org.keycloak.events:DEBUG,org.infinispan:INFO,org.jgroups:INFO"
  - name: KC_PROXY
    value: "edge"


12/18/23
extraEnv: |-
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: KC_PROXY
    value: "edge"
  - name: KC_CACHE
    value: "ispn"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME
    value: "keycloak.10-7-2-63.sslip.io"
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "true"
  - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
    value: "true"
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "password12345"
  - name: KC_HTTPS_CERTIFICATE_FILE
    value: "/opt/keycloak/conf/tls.crt"
  - name: KC_HTTPS_CERTIFICATE_KEY_FILE
    value: "/opt/keycloak/conf/tls.key"
  - name: KC_HTTPS_TRUST_STORE_FILE
    value: "/opt/keycloak/conf/truststore.jks"
  - name: KC_HTTPS_TRUST_STORE_PASSWORD
    value: "password"

kubectl delete -f -<<EOF
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      config:
        use-forwarded-headers: "true"
        extraArgs:
          enable-ssl-passthrough: "true"
EOF