global:
  storageClass: "longhorn"

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.0.0-debian-11-r13
#  pullSecrets:
#  - ironbank-secret
  pullPolicy: Always
  debug: false

containerPorts:
  postgresql: 5432

auth:
  enablePostgresUser: true
  #postgresPassword: ""
  username: "postgres"
  #password: ""
  database: "keycloak"
  replicationUsername: repl_user
  #replicationPassword: ""
  existingSecret: "postgres-credentials"
  secretKeys:
    adminPasswordKey: "POSTGRES_PASSWORD"
    userPasswordKey: "pgUserPassword"
    replicationPasswordKey: "replicationPassword"

primary:
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 0
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

# architecture: standalone
# replication:
#   replication.synchronousCommit: "off"
#   replication.numSynchronousReplicas: 0
#   replication.applicationName: my_application
# ldap:
#   enabled: false
#   server: ""
#   port: ""
#   prefix: ""
#   suffix: ""
#   basedn: ""
#   binddn: ""
#   bindpw: ""
#   searchAttribute: ""
#   searchFilter: ""
#   scheme: ""
#   tls:
#     enabled: false
#   uri: ""