replicas: 1
#
image:
  repository: quay.io/keycloak/keycloak
  tag: "22.0.4"
  digest: ""
  pullPolicy: Always
#
dbchecker:
  enabled: false
  image:
    repository: docker.io/busybox
    tag: 1.32
    pullPolicy: IfNotPresent
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "20m"
      memory: "32Mi"
#
test:
  # If `true`, test resources are created
  enabled: false
  image:
    repository: docker.io/seleniarm/standalone-chromium
    tag: "117.0"
    pullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  deletionPolicy: before-hook-creation
#
imagePullSecrets:
- name: myRegistryKeySecretName
#
podSecurityContext:
  fsGroup: 1000
#
securityContext:
  runAsUser: 1000
  runAsNonRoot: true
#
cache:
  # Use "custom" to disable automatic cache configuration
  stack: default
#
proxy:
  enabled: true
  mode: edge
#
metrics:
  enabled: true
#
health:
  enabled: true
#
# Enable Debugging for KeyCloak POD, remove quotes and uncomment name/value
extraEnv: ""
  # - name: KC_LOG_LEVEL
  #   value: DEBUG
#
resources:
  requests:
    cpu: "500m"
    memory: "1024Mi"
  limits:
    cpu: "500m"
    memory: "1024Mi"
#
statefulsetLabels:
  app: keycloak
#
database:
  # don't create secret for db password. Instead use existing k8s secret
  # existingSecret: "my-existent-dbpass-secret"
  # existingSecretKey: "password"
  existingSecret: ""
  existingSecretKey: ""
  # E.g. dev-file, dev-mem, mariadb, mssql, mysql, oracle or postgres
  vendor:
  hostname:
  port:
  database:
  username:
  password:
#
ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
  labels: {}
  rules:
    - host: "keycloak.10-7-2-141.sslip.io"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - "keycloak.10-7-2-141.sslip.io"
      secretName: ""
  console:
    enabled: true
    ingressClassName: "nginx"
    annotations: {}
    rules:
      - host: "keycloak-console.10-7-2-141.sslip.io"
        paths:
          - path: "/admin"
            pathType: Prefix
    tls:
     - hosts:
         - keycloak-console.10-7-2-141.sslip.io
       secretName: ""